### ISSUE TITLE
Maintenance

### ISSUE THREAD

**Issue by hakkurishian** [saksdirect/SwiftPoet#28]
Is this tool actually still actively maintained? I´m looking for a solution  to generate swift code with a lot of customization including the use of existing swift code so it seems like the best alternative, however without active maintenance.

**Comment by NKorchagin** [comment]
@hakkurishian Hi, this tool s actively used by our projects everyday, SwiftPoet right now is not in active development phase, cause we've done pretty much everything we wanted and it works perfectly more than 2 years already. It's used as CLI tool mostly, if something will break in terms of new APIs/Swift support we will fix it. 

As side note, keep in mind that this is just a tool, so you should provide something more high livel on top to produce some schema and rules what exactly should be generated. In our case it's 2 more levels, but they are private. Those levels generate specific models/structs/enums for us, so we never touch them manually.
